"""initial schema

Revision ID: 5facf0ac50a1
Revises: 
Create Date: 2025-10-13 21:30:26.487542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5facf0ac50a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photosets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('original_archive_filename', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photosets_name'), 'photosets', ['name'], unique=False)
    op.create_index(op.f('ix_photosets_year'), 'photosets', ['year'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_tag_type'), 'tags', ['tag_type'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photoset_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photoset_id'], ['photosets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_file_path'), 'images', ['file_path'], unique=True)
    op.create_index(op.f('ix_images_photoset_id'), 'images', ['photoset_id'], unique=False)
    op.create_table('photoset_tags',
    sa.Column('photoset_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['photoset_id'], ['photosets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photoset_id', 'tag_id')
    )
    op.create_table('captions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('generator_type', sa.String(length=50), nullable=False),
    sa.Column('generator_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_image_id'), 'captions', ['image_id'], unique=True)
    op.create_table('crops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('target_size', sa.Integer(), nullable=False),
    sa.Column('normalized_delta_x', sa.Float(), nullable=False),
    sa.Column('normalized_delta_y', sa.Float(), nullable=False),
    sa.Column('crop_file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_image_id'), 'crops', ['image_id'], unique=True)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('external_vector_id', sa.UUID(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_image_id'), 'embeddings', ['image_id'], unique=False)
    op.create_index(op.f('ix_embeddings_model_name'), 'embeddings', ['model_name'], unique=False)
    op.create_table('image_tags',
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'tag_id')
    )
    op.create_table('thumbnails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('size_name', sa.String(length=20), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnails_image_id'), 'thumbnails', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnails_image_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_table('image_tags')
    op.drop_index(op.f('ix_embeddings_model_name'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_image_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_crops_image_id'), table_name='crops')
    op.drop_table('crops')
    op.drop_index(op.f('ix_captions_image_id'), table_name='captions')
    op.drop_table('captions')
    op.drop_table('photoset_tags')
    op.drop_index(op.f('ix_images_photoset_id'), table_name='images')
    op.drop_index(op.f('ix_images_file_path'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_tags_tag_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_photosets_year'), table_name='photosets')
    op.drop_index(op.f('ix_photosets_name'), table_name='photosets')
    op.drop_table('photosets')
    # ### end Alembic commands ###


